[phases.setup]
nixPkgs = ["php84", "php84Packages.composer", "nginx", "nodejs_20"]

[phases.build]
cmds = [
    "npm run build",
    "php artisan config:cache",
    "php artisan route:cache",
    "php artisan view:cache"
]

[start]
cmd = "php artisan migrate --force && (php-fpm -y $NIXPACKS_PHP_FPM_CONF & nginx -c $NIXPACKS_NGINX_CONF)"
